### ISSUE TITLE
Page not found error while trying to wget

### ISSUE THREAD

**Issue by sanket-media** [eroshenkoam/allure-pdf#27]
used the wget command as mentioned in the readme "wget https://github.com/eroshenkoam/allure-pdf/releases/latest/download/allure-pdf" and it threw an error 404

<img width="960" alt="2023-06-12_19h09_31" src="https://github.com/eroshenkoam/allure-pdf/assets/112850505/eb3a0fc7-518b-43e5-81e4-ce4b729fd4cb">

**Comment by grover11111** [comment]
use command wget https://github.com/eroshenkoam/allure-pdf/releases/latest/download/allure-pdf-1.6.0.zip

**Comment by sanket-media** [comment]
This worked, thank you so much
